### PR TITLE
fix: optimizes querying to use ffetch and new indexes.

### PR DESCRIPTION
**Pull request by mfrisbey**
This PR modifies the following:

* Queries to the index now go through `ffetch` instead of `fetch`.
* Extended `ffetch` so that can be configured to only make a maximum number of chunk requests.
* Author, category, company, and tag templates no longer use javascript to sort, but now use the new `article` index.
* The search template also uses the new `article` index, and has some guard rails in place so that we don't traverse the entire index.
* The related article functionality has also been adjusted to use the `article` index.

The major downside is that this PR essentially limits us to the latest 1,500 articles in the index. As an example, take a category page, which wants to display 13 articles. By default, `ffetch` will "page" through the index until it can come up with 13 articles, after which it will stop. It will continue to page indefinitely until it finds those 13 articles. We definitely don't want to read the entire index (as paging through it would take a very long time), so the site tells `ffetch` only to page until it reads 1,500 total records. This gives us guard rails, but limits most of the site's functionality to the most recent 1,500 articles.

We could tune these settings over time. We're really trying to balance the number of requests to the index, and the size of its responses:

* The higher the `chunk()` size, the larger the responses will be, but there would be fewer requests.
* The lower the `chunk()` size, the smaller the responses will be, but more requests would be sent.
* The higher the `chunkLimit()`, the more records we can process, and more requests would be sent.
* The lower the `chunkLimit()`, the fewer records we can process, and fewer requests would be sent.

One place I think we'll definitely need to revisit it searching. I would think we'd want to allow visitors to search the _entire_ index, which we might not be able to do with `ffetch`. This is where we might eventually want to introduce something more complex.

Test URLs:
- Before: https://main--channelco-crn-com--hlxsites.hlx.page/
- After: https://index-changes--channelco-crn-com--hlxsites.hlx.page/
- After: https://index-changes--channelco-crn-com--hlxsites.hlx.page/news/hp-inc-dwp
- After: https://index-changes--channelco-crn-com--hlxsites.hlx.page/news/components-peripherals/intel-regains-on-pcs-loses-in-servers-against-amd-in-cpu-market-share
- After: https://index-changes--channelco-crn-com--hlxsites.hlx.page/search?query=oracle
- After: https://index-changes--channelco-crn-com--hlxsites.hlx.page/news/computing/
- After: https://index-changes--channelco-crn-com--hlxsites.hlx.page/authors/dylan-martin

### CODE REVIEW

**Comment by mfrisbey** [comment]
The search scores appear to be a fluke - an individual run of that page shows green scores.

**Comment by kunwarsaluja** [comment]
@mfrisbey I see all green with these new changes coming in 👍 

> One place I think we'll definitely need to revisit it searching. I would think we'd want to allow visitors to search the entire index, which we might not be able to do with ffetch. This is where we might eventually want to introduce something more complex.

I would still think at one point of time, the search would still only fetch first 15 latest items for the search term. For this would we still want to parse the full index or we can fetch first 15 with the term and then pagination comes into play which will fetch the next 15 and son ?

**Comment by mfrisbey** [comment]
> @kunwarsaluja   would still think at one point of time, the search would still only fetch first 15 latest items for the search term.

The tricky part is that this favors newer articles (maybe that's ok?), so that it's essentially impossible to access older articles within the site. A search engine might be able to take visitors to older articles, but the site itself would ignore them. Maybe that's not a problem, but it's a limitation within the current implementation. If a search term is only going to be found in older articles, there would be very limited or no results.

**Comment by kunwarsaluja** [comment]
@mfrisbey that's true. maybe we'd want some input from the customer on what they  want the search should do before we create an algorithm for it. 

maybe unrelated, this doesn't fix the display:none on article pages which once refreshed shows the content right ?

Ill approve this as this gets us almost there where we wanted to go with page performance.

**Review by kunwarsaluja — APPROVED** [review]

**Pull request merged**
