### PR TITLE
feat: add article cards block

### LINKED ISSUE #13: [Block] - Cards
- [ ] Mobile version
- [ ] Desktop version
- [ ] Variations
- [ ] Autoblock it (See criteria below and confirm with customer/team)

Before you start, See samples at below urls as there are tiny elements which differ (dotted borders, colors etc.) :
- https://www.crn.com/
- https://www.crn.com/news/hewlett-packard-enterprise-dwp
- https://www.crn.com/news/computing/
- https://www.crn.com/rankings-and-lists
- https://www.crn.com/meet-the-editors/

<hr>

**Note** : In areas where some of the  block variations are used, display criteria can vary as per below so we need to make an informed decision how do we want to architect this block
- published date, sample at https://www.crn.com/news/cloud/
- created by (author), sample at https://www.crn.com/authors/steven-burke
- and more 

<hr>

**Variations**

See if it makes sense to rename the Cards block as a whole to something like News List block so it aligns with IOT site

1. News 

Screenshot 2023-09-14 at 9 51 38 AM

2. (Lead-Article, News)

IMG_2041

Note : In incase we have lead-article variation along with news variation, we need to adapt the Cards layout as per screenshot. Also take into consideration that there could be 1 or 2 Google ads within this context so we need to adapt the layout accordingly. See homepage and one of the category pages to see in action

**NOTE** : On homepage, the cards or news are manually curated but on category pages like **/news/computing/**, would be automated driven the **tag** category & published date driven plus template layout (metadata **template=category**, dummy template is already in /templates/category that we can adjust)

3. Authors

Screenshot 2023-09-14 at 10 45 43 AM

Screenshot 2023-09-14 at 10 44 56 AM

Screenshot 2023-09-21 at 9 06 18 AM
Screenshot 2023-09-21 at 9 05 34 AM

<hr>

**Autoblock criteria**
If in a section , If Cards(Lead-article), Ad block and Cards(News)..Make it structured in way it appears below

Screenshot 2023-09-14 at 9 52 29 AM

### PR DESCRIPTION
**Pull request by mfrisbey**
This is the first pass at adding a cards block. There are several cards described in the ticket, this one is specifically for articles. I renamed the existing `card` block to `article-cards` and added a "Lead-Article" variant.

The default block accepts a list of article URLs:

Screenshot 2023-09-21 at 4 36 07 PM

It will convert those into cards for the target articles:

Screenshot 2023-09-21 at 4 37 01 PM

The Lead-Article variant is similar when authored:

Screenshot 2023-09-21 at 4 37 39 PM

The main difference is it will emphasize the first bullet point and use a grid format:

Screenshot 2023-09-21 at 4 38 39 PM

There are some TODOs to figure out:

* Right now it's using `fetch` to retrieve data from the query index. This approach won't scale, so we'll need to revisit when we have more data.
* We'll need a way to determine an article's "category". Right now I've hard-coded one. We can derive the category's path from the article's URL, but we'll need some way to translate that into the category's display name.
* We may need to revisit some minor padding/formatting in the cards as the site comes together more.

Fix #13

Test URLs:
- Before: https://main--channelco-crn-com--hlxsites.hlx.page/drafts/frisbey/
- After: https://issue-13--channelco-crn-com--hlxsites.hlx.page/drafts/frisbey/

### CODE REVIEW

**Comment by mfrisbey** [comment]
> The variant will disregard any bullets past the first 5.

I was hoping to be able to do the grid layout of the "Lead-Article" variant with pure CSS, but it seems that the number of articles in the grid can be more than 4. So I'll revisit this and come up with a different way.

**Comment by kunwarsaluja** [comment]
@mfrisbey 
 > We'll need a way to determine an article's "category". Right now I've hard-coded one. We can derive the category's path from the article's URL, but we'll need some way to translate that into the category's display name.

We have that field set as tag  on the article level ,see [sample](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/Shared%20Documents/sites/the-channel-company/crn-com/news/managed-services/-painful-decision-slalom-consulting-layoffs-hit-900-workers.docx?d=w4e95e51184b3460fbe4b056309021378&csf=1&web=1&e=ZjWlYw) and should be indexed (can be renamed as '**category**' if it makes more sense, just let @varunmitra know)

**Comment by mfrisbey** [comment]
> @kunwarsaluja  We have that field set as tag on the article level

Nice! Should we assume that matches 1:1 with the parent path of the URL? For example, the URL path of that article is:

```
/news/managed-services/painful-decision-slalom-consulting-layoffs-hit-900-workers
```

I could:

* Display the Tag value from the metadata as the link's text.
* Use the URL's parent path as the href (in this case `/news/managed-services`)

Does that sound ok?

**Comment by kunwarsaluja** [comment]
@mfrisbey  That is valid for all news articles (of template=article) but when it comes to Company pages like [this](https://www.crn.com/news/apple-dwp), we'll be relying on a different metadata (**companynames** set on the article level, was just added today to the live site, will update the content tomorrow)

can't we rely on the 'path' from the index to get the article url ?

**Comment by mfrisbey** [comment]
> @kunwarsaluja can't we rely on the 'path' from the index to get the article url ?

yes, that's what I meant - I misspoke by using URL.

**Comment by kunwarsaluja** [comment]
@mfrisbey  I think 'category' as metadata makes more sense/intuitive here..'tag' is pretty generic. Can you use 'category'  for now ? ill update the  sample content with category in 5mins

@varunmitra Can you please adjust the migration script to make 'category' instead of 'tag'

**Comment by mfrisbey** [comment]
> @kunwarsaluja I think 'category' as metadata makes more sense/intuitive here

Sounds good!

**Review by kunwarsaluja — APPROVED** [review]
Looks clean, Renders well.

If you could change to dynamic 'category', we can merge instantly.

**Comment by mfrisbey** [comment]
@kunwarsaluja FYI, it's now using the `category` value from the index. I also added links to the article, and some aria/accessibility-related properties to the appropriate elements.

**Pull request merged**
