### PR TITLE
feat: place ads in article cards

### LINKED ISSUE #71: [Layout] - Ad layout within Lead article & Article-Cards
See https://main--channelco-crn-com--hlxsites.hlx.page/

**Variation 1**
See crn.com
Lead Article layout needs to be adjust to include ads (there could 1-2) in this section

**Variation 2**
There are other variations in category pages where there is a variation of sponsored ad & advertisement so we need to adjust that part too on the template level
Advertisement : unit-1659132512259
Sponsored ad : unit-1661973671931

See sample at
- https://www.crn.com/news/storage/
- https://www.crn.com/news/computing/

Sample at crn.com
Screenshot 2023-09-27 at 2 46 17 PM
 

Screenshot 2023-09-27 at 2 50 52 PM

### PR DESCRIPTION
**Pull request by mfrisbey**
Places ads within the `lead-article` variant of the `article-cards` block. One ad is placed below the featured article, and another below the sub-articles (but only when there is less than 5 sub-articles).

Fix #71 

Test URLs:
- Before: https://main--channelco-crn-com--hlxsites.hlx.page/
- After: https://issue-71--channelco-crn-com--hlxsites.hlx.page/
- After: https://issue-71--channelco-crn-com--hlxsites.hlx.page/news/computing/

### CODE REVIEW

**Comment by kunwarsaluja** [comment]
@mfrisbey so we're hardcoding the advertisement unit-id here ? Authors won't be able to tweak the unit-id to put another ad in it's place. Does it cater to the scenario where they'd like to adv another sponsored-post type ad underneath the sub articles ? like in the page https://www.crn.com/news/components-peripherals/, would this be handled on the template level ?

I see you can only ad one ad with the same unit-id on the page ? See left-over markup coming from the ad block in the document.
Screenshot 2023-10-10 at 9 22 28 PM

**Comment by mfrisbey** [comment]
> @kunwarsaluja  so we're hardcoding the advertisement unit-id here on the article-cards block level?

Currently, yes. One way to give authors control might be to introduce a new metadata value that can be set on a page (such as `cards-ad-id`). The ID could default to some value, but then authors could override it if needed using the metadata value. WDYT?

> Do we plan to include behavior this on template level as well (category template)?

Yes, see https://issue-71--channelco-crn-com--hlxsites.hlx.page/news/computing/ for an example on the category template. This example also includes the second, sponsored ad.

> I see you can only have ad one ad with the same unit-id on the page?

I didn't notice that - great catch. I'll investigate and see what might be happening.

**Comment by kunwarsaluja** [comment]
> @mfrisbey Currently, yes. One way to give authors control might be to introduce a new metadata value that can be set on a page (such as cards-ad-id). The ID could default to some value, but then authors could override it if needed using the metadata value. WDYT?

Yes i think this is good to have but I don't feel we have do it now now. This is easily extendible if the customer needs it later.

> I see you can only have ad one ad with the same unit-id on the page?

Maybe this is by design but if we are displaying that ad and sponsored post in an automated fashion, maybe we can just remove the incoming ad block from the block.See [here](https://support.google.com/admanager/thread/105253278/multiple-ads-with-single-ad-unit-id-is-possible?hl=en) It can tweaked but do we need to do extra manipulation to achieve this ? maybe not.

**Comment by mfrisbey** [comment]
> maybe we can just remove the incoming ad block from the document

@kunwarsaluja That would be my recommendation. Looking at their live site, they don't have a second ad after the cards - only the ad in the cards. Now that we're loading that ad, I'd propose that we remove the manually curated card from the block. I haven't been able to find a good way to show duplicate ads, but that wouldn't be necessary if we match what's on their current site.

**Review by kunwarsaluja — APPROVED** [review]
removed the ad from the doc source. If incase customers wants to have these ads to be curated and override them, we can introduce this on the page metadata level. Currently what we see, on all pages the ad unit-id is the same for landing pages.

**Pull request merged**
